### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by john-french** [gmit-sweng-20/ca5-bdd-tdd-cycle2-cormacmchale#6]
- Would be nicer if this was a proper mock Movie that returned nothing for `director`, would make it clearer what was going on.
https://github.com/gmit-sweng-20/ca5-bdd-tdd-cycle2-cormacmchale/blob/9794c1512bf2c1d1a7e382e0bd806a65a1b7e590/rottenpotatoes/spec/controllers/movies_controller_spec.rb#L23
- Would be good to verify what happens after the `get` , e.g. is correct template rendered, is correct information available to populate it.
https://github.com/gmit-sweng-20/ca5-bdd-tdd-cycle2-cormacmchale/blob/9794c1512bf2c1d1a7e382e0bd806a65a1b7e590/rottenpotatoes/spec/controllers/movies_controller_spec.rb#L7
- I'd avoid doing any real db interaction here (e.g. use `.new` instead of `.create`)
https://github.com/gmit-sweng-20/ca5-bdd-tdd-cycle2-cormacmchale/blob/9794c1512bf2c1d1a7e382e0bd806a65a1b7e590/rottenpotatoes/spec/controllers/movies_controller_spec.rb#L34
- Possibly a better way to check if an array contains something than iterating over each element manually
https://github.com/gmit-sweng-20/ca5-bdd-tdd-cycle2-cormacmchale/blob/9794c1512bf2c1d1a7e382e0bd806a65a1b7e590/rottenpotatoes/spec/models/movie_spec.rb#L24
- Don't entirely understand this test?
https://github.com/gmit-sweng-20/ca5-bdd-tdd-cycle2-cormacmchale/blob/9794c1512bf2c1d1a7e382e0bd806a65a1b7e590/rottenpotatoes/spec/models/movie_spec.rb#L29

In general tests are thorough and well thought out. Good work.

Please close this issue to acknowledge receipt of feedback.

**Comment by cormacmchale** [comment]
A1
